FROM composer:2 AS step0

WORKDIR /src/

COPY composer.lock /src/
COPY composer.json /src/

RUN composer install --ignore-platform-reqs --optimize-autoloader --prefer-dist

FROM dpokidov/imagemagick:7.1.2-12-bullseye AS imagemagick

FROM php:8.2-cli-bullseye AS final

LABEL maintainer="team@appwrite.io"

COPY --from=imagemagick /usr/local /usr/local

RUN apt-get update \
    && apt-get install -y --no-install-recommends fonts-dejavu ghostscript libbrotli1 libde265-0 libffi-dev libfontconfig1 libfreetype6-dev libgomp1 libjbig0 libjpeg62-turbo-dev liblcms2-2 libomp5 libpng-dev libtcmalloc-minimal4 libtiff5 libwebp-dev libxext6 libxml2-utils x265 \
    && ldconfig \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install -j"$(nproc)" ffi gd \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY --from=step0 /src/vendor /code/vendor

# Add Source Code
COPY ./tests /code/tests
COPY ./src /code/src
COPY ./resources /code/resources
COPY ./phpunit.xml /code/phpunit.xml
COPY ./phpstan.neon /code/phpstan.neon

CMD [ "tail", "-f", "/dev/null" ]
