FROM composer:2 AS step0

WORKDIR /src/

COPY composer.lock /src/
COPY composer.json /src/

RUN composer install --ignore-platform-reqs --optimize-autoloader \
    --no-scripts --prefer-dist

FROM appwrite/utopia-base:php-8.2-0.1.1 AS final

LABEL maintainer="team@appwrite.io"

RUN apk add --no-cache libffi \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS libffi-dev \
    && docker-php-ext-install ffi \
    && apk del .build-deps \
    && printf 'ffi.enable=true\n' > /usr/local/etc/php/conf.d/ffi-enable.ini

WORKDIR /code

COPY --from=step0 /src/vendor /code/vendor

# Add Source Code
COPY ./tests /code/tests
COPY ./src /code/src
COPY ./phpunit.xml /code/phpunit.xml
COPY ./phpstan.neon /code/phpstan.neon

CMD [ "tail", "-f", "/dev/null" ]
