name: "Code Analysis"

on: [ pull_request ]
jobs:
  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2

      - name: Run Static Analysis
        run: |
          docker run --rm -v $PWD:/app composer sh -c \
          "composer install --profile --ignore-platform-reqs && composer check && composer lint"
          