name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Unit & E2E
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: recursive

    - run: git checkout HEAD^2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start and run test
      run:  |
        docker compose up -d
        sleep 10
